import type { Zone } from '@/types';

export const ZONE_TIER_COLORS: Record<string, string> = {
  crown: '#FFB800',
  jungle_deep: '#7C5CFC',
  coral_ridge: '#00C2FF',
  savanna: '#00E096',
  shoreline: '#FF7A35',
};

export const ZONE_STATE_COLORS: Record<string, string> = {
  unclaimed: '#4A5A7A',
  claimed: '#00E096',
  contested: '#FF4757',
  demand: '#FFB800',
};

export const DAR_ZONES: Zone[] = [
  // Crown tier
  {
    id: 'zone-kivukoni-ferry',
    name: 'Kivukoni Ferry Terminal',
    district: 'Kivukoni',
    tier: 'crown',
    type: 'waterfront',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.8160,
    lng: 39.2895,
    radius_meters: 300,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 5,
    daily_yield: 2800,
    upkeep_cost: 280,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'zone-cbd-core',
    name: 'CBD Core',
    district: 'Central',
    tier: 'crown',
    type: 'business_district',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.8160,
    lng: 39.2803,
    radius_meters: 350,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 5,
    daily_yield: 2400,
    upkeep_cost: 240,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },

  // Jungle Deep tier
  {
    id: 'zone-kariakoo-market',
    name: 'Kariakoo Market',
    district: 'Kariakoo',
    tier: 'jungle_deep',
    type: 'street_market',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.8213,
    lng: 39.2724,
    radius_meters: 280,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 4,
    daily_yield: 1800,
    upkeep_cost: 180,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'zone-mlimani-city',
    name: 'Mlimani City',
    district: 'University',
    tier: 'jungle_deep',
    type: 'business_district',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.7714,
    lng: 39.2369,
    radius_meters: 260,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 4,
    daily_yield: 1600,
    upkeep_cost: 160,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },

  // Coral Ridge tier
  {
    id: 'zone-masaki-peninsula',
    name: 'Masaki Peninsula',
    district: 'Masaki',
    tier: 'coral_ridge',
    type: 'rooftop',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.7747,
    lng: 39.2786,
    radius_meters: 240,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 3,
    daily_yield: 1200,
    upkeep_cost: 120,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'zone-posta-junction',
    name: 'Posta Junction',
    district: 'Central',
    tier: 'coral_ridge',
    type: 'transit_hub',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.8127,
    lng: 39.2821,
    radius_meters: 220,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 3,
    daily_yield: 900,
    upkeep_cost: 90,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'zone-magomeni-night',
    name: 'Magomeni Night Market',
    district: 'Magomeni',
    tier: 'coral_ridge',
    type: 'night_market',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.7982,
    lng: 39.2598,
    radius_meters: 200,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 3,
    daily_yield: 1000,
    upkeep_cost: 100,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },

  // Savanna tier
  {
    id: 'zone-kinondoni-residential',
    name: 'Kinondoni Residential',
    district: 'Kinondoni',
    tier: 'savanna',
    type: 'residential',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.7841,
    lng: 39.2521,
    radius_meters: 180,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 3,
    daily_yield: 700,
    upkeep_cost: 70,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'zone-ubungo-bus',
    name: 'Ubungo Bus Terminal',
    district: 'Ubungo',
    tier: 'savanna',
    type: 'transit_hub',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.7989,
    lng: 39.2285,
    radius_meters: 190,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 3,
    daily_yield: 600,
    upkeep_cost: 60,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },

  // Shoreline tier
  {
    id: 'zone-sinza-street',
    name: 'Sinza Street',
    district: 'Sinza',
    tier: 'shoreline',
    type: 'residential',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.7892,
    lng: 39.2423,
    radius_meters: 150,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 2,
    daily_yield: 350,
    upkeep_cost: 35,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'zone-temeke-market',
    name: 'Temeke Market',
    district: 'Temeke',
    tier: 'shoreline',
    type: 'street_market',
    state: 'unclaimed',
    owner_id: null,
    owner_handle: null,
    owner_color: null,
    lat: -6.8621,
    lng: 39.2712,
    radius_meters: 160,
    claim_strength: 0,
    traces: [],
    trace_count: 0,
    contested_threshold: 2,
    daily_yield: 300,
    upkeep_cost: 30,
    task_demand: null,
    infrastructure: [],
    created_at: new Date().toISOString(),
  },
];
